# App Registry - managed by deploy.sh / remove.sh
# Format: name|slot|repo|status|npm_host_id|frontend_service|frontend_port|app_ip|npm_ip_host_id
dndproject|1|https://github.com/masymasy94/DnDSupportProject.git|running||gateway|80|192.168.3.200|
hasasierofy|2|https://github.com/masymasy94/Hasasierofy.git|running|manual|api|8000|192.168.3.201|
hasasieroshopping|3|https://github.com/masymasy94/HasasieroShopping.git|running|manual|app|3000|192.168.3.202|
